### ISSUE TITLE
Selecting nodes causes exception when using immutable library (Immer with Redux Toolkit)

### ISSUE THREAD

**Issue by dsoklic** [xyflow/xyflow#3904]
### Describe the Bug

I'm using Redux Toolkit for my application. When I select a few nodes by drawing a rectangle, I get the exception that says: Cannot assign to read only property 'selected' of object '#<Object>'.

This issue happens because Redux Toolkit uses Immer under the hood, but React-flow tries to mutate the data.
I was able to track down the issue to the `getSelectionChanges` function, where the selected property is mutated.

I tested this on React-flow v11.10.1 and v12, it happens with both.

### Your Example Website or App

https://codesandbox.io/p/sandbox/selection-with-redux-reactflow11-mkd4ql

### Steps to Reproduce the Bug or Issue

1. Press and hold down Shift
2. Start drawing the selection rectangle. Try moving it around, selecting and unselecting a few nodes. Keep selecting and unselecting nodes for a few seconds.

Very soon you should get the exception.

### Expected behavior

No exception should be thrown

### Platform

- OS: Windows
- Browser: Brave and Electron
- Version: Brave v1.62.156

### Additional context

Seems to be related to https://github.com/xyflow/xyflow/issues/2170

**Comment by peterkogo** [comment]
@dsoklic I can't open your sandbox. If you update it, I can take a look

**Comment by dsoklic** [comment]
@peterkogo Sorry, I didn't change the permissions to the sandbox. Could you try it again?

**Comment by gorbatkoff** [comment]
Any updates?

**Comment by moklick** [comment]
Hey, could you check with the latest v12 release?

**Comment by dsoklic** [comment]
@moklick I tried it out, and I still get this issue. It required some more selecting and unselecting, but eventually, I got the same error. Link to the sandbox: [link](https://codesandbox.io/p/sandbox/selection-with-redux-reactflow11-forked-fyrfkw)

**Comment by gorbatkoff** [comment]
In another issue the guy advised making the state immutable
https://github.com/xyflow/xyflow/issues/2240
[
<img width="972" alt="Снимок экрана 2024-04-16 в 11 11 22" src="https://github.com/xyflow/xyflow/assets/97447842/b9a99250-be1f-4df8-8b0c-85fcd068bb56">](https://github.com/xyflow/xyflow/issues/2240#issuecomment-1164231753)

**Comment by moklick** [comment]
@dsoklic thanks for the codesandbox! I can't repro it with v12 there 🤔

**Comment by dsoklic** [comment]
@moklick I recorded a video, so you can see what steps I did: [video](https://streamable.com/aylkbs)

Sometimes you need to keep selecting and unselecting for a while to get this error. In my video, it just coincidentally happened so fast.

**Comment by dsoklic** [comment]
> In another issue the guy advised making the state immutable #2240 [ <img alt="Снимок экрана 2024-04-16 в 11 11 22" width="972" src="https://github.com/xyflow/xyflow/assets/97447842/b9a99250-be1f-4df8-8b0c-85fcd068bb56">](https://github.com/xyflow/xyflow/issues/2240#issuecomment-1164231753)

The replies in that thread already say what I wanted to say: using a state management library is recommended in the docs, and making the state immutable is a feature that avoids issues. React Flow shouldn't be mutating the state.

**Comment by moklick** [comment]
@dsoklic thanks, now I get it too. I will check it!

**Comment by moklick** [comment]
The reason for this bug is the `onSelectionChange` handler. Will be fixed in the next release - for now you can can remove the handler and it should work as expected.

**Comment by gorbatkoff** [comment]
When will the next release be?
And what will be the title of the release? 11.11.2?

**Comment by moklick** [comment]
Fixed in 11.11.2 and 12.0.0-next.15

**Comment by gorbatkoff** [comment]
<img width="292" alt="Снимок экрана 2024-04-23 в 13 48 03" src="https://github.com/xyflow/xyflow/assets/97447842/0359485e-6e17-4f9d-9f4c-ae6634eb4c6e">

<img width="476" alt="Снимок экрана 2024-04-23 в 13 46 56" src="https://github.com/xyflow/xyflow/assets/97447842/eb10c927-9ad0-46a9-9827-0cd281c6baf5">

I still get this error even after installing 11.11.2

**Comment by gorbatkoff** [comment]
I found a solution for preventing this error, but it looks not good.
Look at the commented code. 

<img width="631" alt="Снимок экрана 2024-04-23 в 13 49 13" src="https://github.com/xyflow/xyflow/assets/97447842/b9e80369-9baa-4f05-a22d-8d264aa1a2f3">
