### ISSUE TITLE
applyNodeChanges doesn't work with immer

### ISSUE THREAD

**Issue by fredericrous** [xyflow/xyflow#4253]
### Describe the Bug

I manage the state of react flow with zustand, I do this coz I implemented undo/redo

I'm using immer with zustand, indeed I noticed that using immer helps me to not forget nested object copy, and keep a shorter code.

So I followed the documentation and it suggest to implement the function `onNodesChange` in my store and pass it to ReactFlow component.

here is the code I'm referring to

```ts
    onNodesChange(changes) {
      set((state) => {
        state.nodes = applyNodeChanges(
          changes,
          get().nodes,
        );
      });
    },
```

immer doesn't like it

```console
Uncaught TypeError: Cannot assign to read only property 'width' of object '#<Object>'
    at applyChange (index.mjs:555:34)
    at applyChanges (index.mjs:530:13)
    at applyNodeChanges (index.mjs:590:12)
    at triggerNodeChanges (index.mjs:2700:38)
    at updateNodeInternals (index.mjs:2660:13)
    at ResizeObserver.<anonymous> (index.mjs:1663:13)
```

<img width="907" alt="image" src="https://github.com/xyflow/xyflow/assets/702227/b2f3b0db-af95-4a45-9c60-3545056faca2">

I tried a hack

```ts
    onNodesChange(changes) {
      set((state) => {
        state.nodes = applyNodeChanges(
          changes,
          JSON.parse(JSON.stringify(get().nodes)),
        );
      });
    },
```

... and it is kinda working, however I ran into the same exception but from code within the lib

```ts
    triggerNodeChanges: (changes) => {
        const { onNodesChange, setNodes, nodes, hasDefaultNodes, debug } = get();
        if (changes?.length) {
            if (hasDefaultNodes) {
                const updatedNodes = applyNodeChanges(changes, nodes); // <= it throws from right there
                setNodes(updatedNodes);
            }
            if (debug) {
                console.log('React Flow: trigger node changes', changes);
            }
            onNodesChange?.(changes);
        }
    },
```

This issue might be related to the closed issue https://github.com/xyflow/xyflow/issues/3904

### Steps to Reproduce the Bug or Issue

install immer, follow the tutorial https://reactflow.dev/learn/tutorials/react-flow-and-the-web-audio-api#1-state-management-with-zustand

### Expected behavior

implement applyNodeChanges to be compatible with Immer? or create a second function applyNodeChangesPure?

### Platform

- OS: macOS 12.5
- Browser: Chrome 124.0.6367.91 
- Version: 12.0.0-next.17

**Comment by fredericrous** [comment]
instead of JSON.parse/stringify I implemented immer produce. I cannot reproduce the issue with `triggerNodeChanges` anymore. closing for now

**Comment by fredericrous** [comment]
with 12.0.0-next.19 I was able to reproduce the issue coming from triggerNodeChanges.
Solution was to copy the nodes before passing them to ReactFlow component

```ks
<ReactFlow nodes={structuredClone(nodes) as ReactFlowNode[]}
```

**Comment by HiChen404** [comment]
same problem

**Comment by dqhieuu** [comment]
It still happens, mostly because `applyNodeChanges` and `applyEdgeChanges` call `applyChanges` method, which modifies the immutable edges and nodes created by immer's `produce`.

Knowing that `applyNodeChanges` mutates the current state, I proceeded to create my own `onNodesChange`, and found something very awkward with the current React flow's implementation. So my implementation was

```
  const onNodesChange = (changes: NodeChange[]) => {
    const updatedNodes = produce(nodes, (draft) => {
      applyNodeChanges(changes, draft););
    });
    setNodes(updatedNodes);
  };
```

But nothing changed, even though this method mutated the nodes!

Then I tried returning the new object 
```
  const onNodesChange = (changes: NodeChange[]) => {
    const updatedNodes = produce(nodes, (draft) => {
      return applyNodeChanges(changes, draft););
    });
    setNodes(updatedNodes);
  };
```
Immer immediately threw `Error: An immer producer returned a new value *and* modified its draft. Either return a new value *or* modify the draft`?

I came to realize that this method behavior is half-assed at mutating. Specifically, it changes some parts of the nodes object, but then finally aggregates into a new object instead of returning the old mutated object. And this fucks up immer's behavior to either accept a newly returned object or use the old draft object. So I had to work around by shallow-copying each element to the new draft.

```
  const [nodes, setNodes] = useNodesState([] as Node[]);
  const onNodesChange = (changes: NodeChange[]) => {
    const updatedNodes = produce(nodes, (draft) => {
      const entries = applyNodeChanges(changes, draft);
      draft.splice(0, entries.length, ...entries);
      draft.splice(entries.length);
    });
    setNodes(updatedNodes);
  };
```
And it finally worked.

@moklick Anyway, the current implementation sounds like a bad practice, and doesn't integrate well with immer, which is a fairly popular library. So could you check this code? Thank you!

https://github.com/xyflow/xyflow/blob/80177925425b630187a769f45a813da3cb623ee8/packages/react/src/utils/changes.ts#L20

**Comment by EvgenyArtemov** [comment]
> It still happens, mostly because `applyNodeChanges` and `applyEdgeChanges` call `applyChanges` method, which modifies the immutable edges and nodes created by immer's `produce`.
> 

Did you try to use structuredClone from comment above? It seems to be working for me. Anyway thanks for sharing your solution, I hope I will end up with working structuredClone...
