### ISSUE TITLE
v11 --> v12 breaks edge position and placement when loading images

### ISSUE THREAD

**Issue by hsab** [xyflow/xyflow#4528]
### What platform were you using when you found the bug?

```bash
  System:
    OS: Linux 6.6 Manjaro Linux
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
  Browsers:
    Chromium: 127.0.6533.88
  npmPackages:
    @xyflow/react: ^12.0.4 => 12.0.4 
    next: ^14.2.3 => 14.2.3 
    react: ^18.3.1 => 18.3.1 
    typescript: 5.5.4 => 5.5.4 
```

### Describe the Bug

I just updated my repo to the latest version of RF and I noticed that the behavior of the edge placement and updating has changed. Specifically when loading dynamic content such as videos and images, the edges used to update automatically. This also applied when dealing with dynamic CSS modifications (e.g changing the height of something in the node).

I deal with unknown content, so there's no way to prevent layout shifts. Also the scope and the number of images, make it unfeasible to constantly track image loading state and then call `useUpdateNodeInternals`.

## V11
Position is correct, after content is loaded edges are updated.
![Screenshot_2024-08-07_17-10](https://github.com/user-attachments/assets/579ef00b-b584-4bef-af13-fef43c7454ce)

## V12
Position is incorrect, after content is loaded edges remain where they were mounted initially.
![Screenshot_2024-08-07_17-09](https://github.com/user-attachments/assets/ac5f10e5-f43c-45ff-879d-1ec73207f307)

I'm wondering what has changed specifically that has caused this issue? Is this is design choice on your behalf and expected behavior? 

### Steps to reproduce the bug or issue

This can be tried using the custom node example with a large image

### Expected behavior

I expect the edges to automatically shift to correct position.

**Comment by peterkogo** [comment]
This definitely seems like a bug. We still very much support dynamically resized nodes. 
Is there a chance you add the handles dynamically after the image has loaded?

**Comment by hsab** [comment]
@peterkogo I add the handles before the image is loaded. In this case the handles are always present. 

This is the gist of the nodes on the right side, sorry if there are too many abstractions. 
```tsx
    <BaseNode
      {...nodeProps}
      className={cn('w-[15rem]', nodeData.inputs.image?.data && 'w-[30rem]')}
      pureNodeComponent={
        PureImageViewerNode as TypePureNodeComponent<TypeImageViewerNode>
      }
      hideMenuBar
    >
      <div className="flex flex-col gap-2 !bg-transparent !p-0">
        <div className="relative flex flex-col gap-2 rounded-b-xl rounded-t-lg p-0">
          {Object.values(nodeData?.outputs || {}).map((output) => (
            <SocketOutput output={output} key={output.id} />
          ))}
          {Object.values(nodeData?.inputs || {}).map((input) => (
            <SocketInput input={input} key={input.id} showLabel={false} />
          ))}

		  
          {!nodeData.inputs.image?.data ||
          nodeData.inputs.image?.data === '' ? (
            <div className="flex aspect-square h-full w-full items-center justify-center rounded-xl bg-neutral-900 text-center text-xs text-neutral-500">
              <Icon
                icon="solar:gallery-bold"
                width="100%"
                className="w-8 text-neutral-400"
              />
            </div>
          ) : (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={nodeData.inputs.image?.data}
              alt="Displaying input"
              className={cn(
                'rounded-xl',
                'outline outline-[0.125rem] outline-offset-4 outline-neutral-300/0 duration-300',
              )}
            />
          )}
        </div>
      </div>
    </BaseNode>
```

**Comment by hsab** [comment]
Seems to be only happening with images. I replaced the image in one of the nodes with a square `div`. Seems to be working fine in that case

## Before
![Screenshot_2024-08-08_14-27](https://github.com/user-attachments/assets/df0f81e8-7d0d-44bc-86bd-08f2a1ed31de)


## After
![image](https://github.com/user-attachments/assets/0541cd68-48c2-4775-bd93-845fe5e62ef3)

**Comment by moklick** [comment]
Thanks for bringing this up. It should work automatically, since nodes change their dimensions. We will check it!

**Comment by alexanderhorner** [comment]
I think I'm running into a similar issue with dynamically sized nodes, probably due to the new `node.measured` stuff. I'll see if I can reproduce it.

The migration from v11 to v12 has turned out to be more challenging than I expected.

**Comment by moklick** [comment]
I can't reproduce this issue https://codesandbox.io/p/sandbox/sad-estrela-t22fx7?file=/src/nodes/index.ts - It would be super helpful if you could create an example for this.

@alexanderhorner That's sad to hear! If you find some time, you could open an issue or just write us a mail with your experiences.

**Comment by hsab** [comment]
I think I found the issue while creating the reproduction repo. The violating node attributes are `width` and `height`. If these are present dynamic positioning breaks. Rereading the [docs](https://reactflow.dev/learn/troubleshooting/migrate-to-v12) I can see that `Using width and height now means that the dimensions are not dynamic based on the content but fixed.` smh

**Comment by bcakmakoglu** [comment]
I was about to comment the same 😄 
Good that you figured it out yourself though 👍

**Comment by moklick** [comment]
Nice, that you could solve it already. That's one of the biggest changes with React Flow 12.

**Comment by hsab** [comment]
Wondering if width and height should be ignore if measured is present? @moklick

**Comment by moklick** [comment]
`measured` is not something that is set by the user but whenever the resize observer detects a change and on first render.

**Comment by alexanderhorner** [comment]
My issue seems to arise from measured not being calculated correctly during the initial render. I rely heavily on custom edge logic that depends on width and height. It would be fine if it immediately re-rendered once the heights are known, but that doesn’t seem to be happening. Additionally, I'm facing issues when the size of a node changes due to content.

I'm not entirely sure what change is causing this. Another problem I'm encountering is an error in applyNodeChanges, also related to measured height/width (dimension change). It indicates that the object is read-only, but I haven't been able to reproduce this consistently either.

**Comment by hsab** [comment]
@moklick I still encounter strange issues with `initialWidth/Height`. This happens specifically when I throttle my connection using chrome's dev tools to Slow 3G, and the edges fail to be positioned properly. On speedy connections everything works as expected. 

Also  opening this up again for @alexanderhorner.

**Comment by moklick** [comment]
@hsab could you update the repo you've posted yesterday? I can't reproduce the throttled network issue.

@alexanderhorner if you have a repo or codesandbox that would help!

**Comment by alexanderhorner** [comment]
I was working on a minimal reproduction, but unfortunately, I can't spend more time on this, at least for now.

My custom edge tries to find the closest edge and also uses node.measuredDimensions for that. However, when the dimensions change, the edge is not rerendered.

This could be fixed by providing a way to subscribe to these changes using the Zustand store.

I had a similar problem with the edge not re-rendering when the position of the actual handles changes. The fix was to subscribe to the internal handleBounds object and re-render the edge if something changes.

```ts
  const sourceHandleBounds = useStore(reactFlowStore, s => s.nodeLookup.get(source)?.internals.handleBounds)
  const targetHandleBounds = useStore(reactFlowStore, s => s.nodeLookup.get(target)?.internals.handleBounds)
  ```

Seems like a hacky work around.

**Comment by alexanderhorner** [comment]
The other problem is happening here:

```ts
onNodesChange: (changes) => {
  const nodes = get().nodes
  set({
    nodes: applyNodeChanges(changes, nodes) as TableNode[],
  })
}
```

```
index.mjs:582  Uncaught TypeError: Cannot assign to read only property 'width' of object '#<Object>'
    at applyChange (index.mjs:582:34)
    at applyChanges (index.mjs:557:13)
    at applyNodeChanges (index.mjs:617:12)
    at createReactFlowSlice.ts:48:16
 ```
 
 Adding structuredClone seems to fix that issue.
 
```ts
onNodesChange: (changes) => {
  const nodes = structuredClone(get().nodes) // like the old JSON.parse(JSON.stringify(get().nodes)) hack
  set({
    nodes: applyNodeChanges(changes, nodes) as TableNode[],
  })
}
```

I tried reproducing this issue in CodeSandbox but wasn't able to. I would love to spend more time on this, but something else came up, so we've put the React Flow 12 update on hold for now. Hopefully, this information is still useful to you.

**Comment by alexanderhorner** [comment]
Fixed the edge calculations by also applying the same subscribe "hack"

```ts
  const targetDimensions = useStore(reactFlowStore, s => s.nodeLookup.get(source)?.measured)
  const sourceDimensions = useStore(reactFlowStore, s => s.nodeLookup.get(target)?.measured)
  ```
  
  Now the custom edge rerenders when the measured dimensions change.

**Comment by hsab** [comment]
@moklick hmmm can't seem to reproduce the issue anymore. so that's good news! :) Will report back if it happens again. Cheers!

**Comment by moklick** [comment]
removing `width` and `height` fixed it for you @hsab ?

**Comment by hsab** [comment]
@moklick so at first I was using `width` and `height` incorrectly and the edges were not positioning properly. Removing those fixed the issue so I decided to explore `initialWidth` and `initialHeight`. With the initial values the edges were not positioning probably on slow networks (3G and Slow 3G). But since this morning there issue has been fixed and I really didn't change anything so I'm wondering what could have caused it.

I'm going to continue using the initial values because I save the store to an online database so the user can access it later on. And when I am saving the store I basically use the measured values for width and height to set the initial properties. 

So far it seems to have been magically fixed. But since I'm using initialWH values I assume if it's an actual bug it's going to resurface again and if it does so I'll report back here.

I really appreciate your help though. You guys have amazing support and have built an incredible product! Kudos

**Comment by moklick** [comment]
Thanks for the update and your kind words! I will leave this open for a bit longer until we figured out what is happening with initialWidth/Height and wait for @alexanderhorner s feedback.

btw @hsab what are you building with React Flow?

**Comment by hsab** [comment]
@moklick bad news! the issue is still there. It is inconsistent, sometimes it works, sometimes it doesn't. Behaves unexpectedly on each visit, but more interestingly it behaves different in the same graph. So some edges are correct, some misaligned. See this photo. Green is good, red is bad

![image](https://github.com/user-attachments/assets/106cb3eb-af14-4215-b67e-9a5dfe7ec950)


 I can't seem to reproduce this out side of my app, need to investigate more. 
 
 ps. we're building a node-based creative suite for media processing. still in stealth but will definitely share once we're ready :)

**Comment by moklick** [comment]
We will investigate.

**Comment by peterkogo** [comment]
@hsab just spitballing here, are you by any chance using custom edges as well or just the built-in ones?

**Comment by peterkogo** [comment]
This seems like a very weird edge case, since `initialWidth/-Height` might be the cause of this. But this could also be some kind of race condition of the way you render your handles programmatically (even though you are using keys).
 If you are interested, we can connect on our [Discord](https://discord.gg/RVmnytFmGW) to get to the bottom of this.

**Comment by hsab** [comment]
hi @peterkogo! I will reach out on discord for sure. appreciate you lending a hand. I agree that there's something really weird going on. To answer you earlier question, I do use custom edges but only as a placeholder for future development. This is how it's currently coded

```tsx
import {
  BaseEdge,
  EdgeProps,
  Position,
  getSimpleBezierPath,
} from '@xyflow/react';
import React from 'react';

const CustomEdge = ({
  sourceX,
  sourceY,
  targetX,
  targetY,
  ...props
}: EdgeProps) => {
  const [edgePath] = getSimpleBezierPath({
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
  });

  return <BaseEdge path={edgePath} {...props} />;
};

export default CustomEdge;
```

**Comment by alexanderhorner** [comment]
> The other problem is happening here:
> 
> ```ts
> onNodesChange: (changes) => {
>   const nodes = get().nodes
>   set({
>     nodes: applyNodeChanges(changes, nodes) as TableNode[],
>   })
> }
> ```
> 
> ```
> index.mjs:582  Uncaught TypeError: Cannot assign to read only property 'width' of object '#<Object>'
>     at applyChange (index.mjs:582:34)
>     at applyChanges (index.mjs:557:13)
>     at applyNodeChanges (index.mjs:617:12)
>     at createReactFlowSlice.ts:48:16
> ```
> 
> Adding structuredClone seems to fix that issue.
> 
> ```ts
> onNodesChange: (changes) => {
>   const nodes = structuredClone(get().nodes) // like the old JSON.parse(JSON.stringify(get().nodes)) hack
>   set({
>     nodes: applyNodeChanges(changes, nodes) as TableNode[],
>   })
> }
> ```
> 
> I tried reproducing this issue in CodeSandbox but wasn't able to. I would love to spend more time on this, but something else came up, so we've put the React Flow 12 update on hold for now. Hopefully, this information is still useful to you.

So I figured out what the issue was. I'm using zustand together with immer. Turns out immer freezes objects deeply. But applyNodeChanges mutates the `measured ` object inside a node.

The other issue I had was also resolved by me subscribing to the changes manually by going into the reactflow store. Still feels a bit hacky and I wish there was a better solution for that.

**Comment by hsab** [comment]
@alexanderhorner for your immer issues, I think you can use `current` or the `original` methods from immer. Performance is much faster than `structuredClone` and actually even 2x faster than `const { nodes } = state`
additionally I highly recommend disabling [autofreeze](https://immerjs.github.io/immer/freezing) via `setAutoFreeze(false)`

```tsx
onNodesChange: (changes: NodeChange[]) => {
  set((state) => {
    const { nodes } = current(state);
    state.nodes = applyNodeChanges(changes, nodes);
  });
}
```

**Comment by alexanderhorner** [comment]
Yes it was auto freeze, took a long time to figure out...

Why is `const { nodes } = current(state)` faster then `const { nodes } = get()` (get the method from the zustand store)?

**Comment by hsab** [comment]
@alexanderhorner I actually have no idea! I just noticed it as I was testing the performance of my `onNodeChanges`  method. But if I were to guess, I'd say by using `current` you're essentially bypassing all the proxy logic. Without `currentc` the function below was hitting 0.8ms while using `current` brought it down to 0.3ms. 

To be clear, the performance gain can also be specific to my implementation. My nodes and edges are stored as key/value objects  instead of the default array[] format that is recommended by RF. So I have to do some logic here and there for updates/sets, but the key/val setup makes it much easier to access and modify individual nodes. outside of react components where I don't have access to hooks, without incurring a O(n) search penalty. 

this is my actual function

```ts
onNodesChange: (changes: NodeChange[]) => {
  set((state) => {
    const { nodes } = current(state);

    const changedNodes = applyNodeChanges(
      changes,
      Object.values(nodes) as Node[],
    ) as AnyFuserNode[];

    for (const change of changes) {
      if (change.type === 'remove') {
        delete state.nodes[change.id];
      }

      if (
        change.type === 'select' &&
        !change.selected &&
        state.lastAddedNode === change.id
      ) {
        state.lastAddedNode = undefined;
      }
    }

    for (const node of changedNodes) {
      state.nodes[node.id] = castDraft(node);
    }
    state.lastUpdate = Date.now();
  });
},
```

**Comment by ThimoDEV** [comment]
I have the same error but can't precisely reproduce it. I don't use immer. I do programmatically change the size of nodes on hover. Disabling that doesn't solve it.

**Comment by moklick** [comment]
@ThimoDEV are you working with a custom onNodesChange implementation?

**Comment by ThimoDEV** [comment]
> @ThimoDEV are you working with a custom onNodesChange implementation?

`
const [nodes, setNodes, onNodesChange] = useNodesState<Node>([]);
  onNodesChange={(changes) => {
          onNodesChange(changes);
        }}
`

I use this, its the most basic I can have else nothing gets rendered. Can I let reactflow take over this part or something?

**Comment by hsab** [comment]
> Should we keep this issue open? Is this still an issue @hsab and @alexanderhorner ?

still experiencing edge mis-placement when using `initialWidth` and `initialHeight`

**Comment by hsab** [comment]
@moklick I actually managed to fix the issue! There was in fact a race condition going on with one of my useEffects @peterkogo tysm for the tip! 🙏🏼

**Comment by peterkogo** [comment]
Great! I will close this for now. Don't hesitate to reopen this issue or to write us on DIscord  if the problem persists.
